#define ENCRYPTKEY "mysecretpassword"
#define NODE_BASE 1
#define NODE_ETAGE 2
#define NODE_SALON 3
#define NODE_JARDIN 4
#define NODE_THERMOSTAT 5
#define NODE_EDF 6
#define NODE_GRENIER 7
#define RFM69Retry 3
#define RFM69RetryTimeout 40